Pass through redirect query arg
jazzband/django-invitations pull request #233
Opened 2023-10-17 20:29 UTC by blag

Fixes #231.

Pass through a `next=...` query parameter to the signup and login views.

The docs for [`SIGNUP_REDIRECT`](https://github.com/jazzband/django-invitations/blob/master/docs/configuration.rst#signup_redirect) and [`LOGIN_REDIRECT`](https://github.com/jazzband/django-invitations/blob/master/docs/configuration.rst#login_redirect) indicate they should be a URL _name_, the default values for these settings are URL names, and the tests for the allauth backend do not override those options and so expect a URL name.

But the [tests for the basic backend](https://github.com/jazzband/django-invitations/blob/a81617da3415fe5f807e575c8d81e6c38b636592/tests/basic/tests.py) override that option with a direct URL:

```python
        settings.INVITATIONS_LOGIN_REDIRECT = "/login-url/"
        ...
        settings.INVITATIONS_LOGIN_REDIRECT = "/login-url/"
        ...
        settings.INVITATIONS_SIGNUP_REDIRECT = "/signup-url/"
        ...
        settings.INVITATIONS_SIGNUP_REDIRECT = "/non-existent-url/"
        ...
        settings.INVITATIONS_SIGNUP_REDIRECT = "/non-existent-url/"
        ...
    @override_settings(INVITATIONS_SIGNUP_REDIRECT="/non-existent-url/")
    ...
        settings.INVITATIONS_LOGIN_REDIRECT = "/login-url/"
```

Which is why I do this in this PR:

```python
        try:
            signup_redirect = reverse(app_settings.SIGNUP_REDIRECT)
        except NoReverseMatch:
            signup_redirect = app_settings.SIGNUP_REDIRECT
        ...
        try:
            login_redirect = reverse(app_settings.LOGIN_REDIRECT)
        except NoReverseMatch:
            login_redirect = app_settings.LOGIN_REDIRECT
```

Fixing this may not be backwards compatible with existing users. It is also best left for a separate discussion, so for this PR I allowed for both options.

I also removed the walrus operator in a separate commit, so once we drop support for Python 3.7 we can revert that single commit to use the walrus operator.

2023-10-17 21:16 UTC, blag commented
pre-commit.ci autofix

2023-12-01 22:22 UTC, valberg commented
Hi @blag 

Nice work! :clap: 

Python 3.7 has been dropped in 2.1.0 - so we can revert the mentioned commit :blush: 

Also there is a conflict.

I'll approve and merge when those issues are resolved :+1:

2023-12-01 22:23 UTC, valberg requested changes
Reintroduce the walrus operator :seal: 

Fix conflict.

:rocket:

2023-12-07 08:08 UTC, blag commented
Removed commit and fixed conflict.

2023-12-07 08:53 UTC, valberg approved these changes
Awesome! :clap:

2023-12-07 08:53 UTC, merged

2023-12-15 01:30 UTC, blag commented
Hey @valberg, thanks for the merge.

Do you mind tagging a release? I have a project that needs my fix and I'd like to specify a version instead of a commit hash for it. 😄